version: '3.8'

services:
  api:
    container_name: chatbot-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - AUTH_BYPASS_ENABLED=true
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge