name: CI

on:
  push:
    branches: [ main, develop, prepare-template ]
  pull_request:
    branches: [ main, develop, prepare-template ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ENVIRONMENT: test
          AUTH_BYPASS_ENABLED: "true"
          
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: chatbot-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app-code
          path: |
            .
            !venv/
            !.git/
