name: Deploy to Railway

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-code
          path: .
        # Skip if manually triggered
        if: github.event_name == 'workflow_run'
        
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
