
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Navigate to backend directory
        run: |
          cd backend
          echo "Current directory: $(pwd)"
          ls -la
          
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: List files in directory
        working-directory: ./backend
        run: ls -la
          
      - name: Run tests with MongoDB Atlas
        working-directory: ./backend
        run: |
          echo "Running tests with MongoDB Atlas"
          pytest -v
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          ENVIRONMENT: test
          AUTH_BYPASS_ENABLED: "true"
          
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: false
          tags: chatbot-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app-code
          path: |
            ./backend
            !./backend/venv/
            !.git/
